baseURL = 'https://clim.dev'
languageCode = 'en-us'
title = 'CLIM DEV blog'
theme = "lim"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "blog"
    pre = "pen-tool"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3